"""Project-owned agent observability, replay, and evaluation primitives."""

from .recorder import TraceRecorder
from .evidence_policy import (
    EvidencePolicyDecision,
    EvidencePolicyGuard,
    EvidencePolicyMode,
    EvidencePolicyVerdict,
)
from .planner_eval import (
    ParsedPlannerPrediction,
    PlannerDecisionEvaluation,
    PlannerPredictionRecord,
    PlannerPredictionError,
    aggregate_planner_evaluations,
    evaluate_planner_prediction,
    evaluate_prediction_records,
    parse_planner_prediction,
    tool_family,
)
from .planner_budget import (
    FORCED_STOP_FLAG,
    PLANNER_BUDGET_PROTOCOL,
    PlannerBudgetMiddleware,
    PlannerBudgetState,
    count_prior_tool_calls,
    inject_budget_state_into_messages,
    planner_budget_state,
    render_budget_prompt,
)
from .planner_sft import (
    PlannerSftConversionError,
    assistant_supervision_indices,
    planner_decision_to_sft_example,
    write_planner_sft_jsonl,
)
from .replay import (
    CACHE_SCHEMA_VERSION,
    ObservationCache,
    ObservationCacheEntry,
    ObservationCacheStore,
    ReplayCacheConflict,
    ReplayCacheMiss,
    ReplayError,
    ReplaySession,
    ReplayTranscript,
    canonical_tool_signature,
    content_digest,
    rebuild_transcript,
)
from .schema import EventKind, RunOutcome, TraceEvent
from .scenario import (
    DECISION_POINT_SCHEMA_VERSION,
    SCENARIO_SCHEMA_VERSION,
    PlannerAction,
    PlannerActionKind,
    PlannerDecisionPoint,
    ReplayScenario,
    ReplayScenarioStore,
    ScenarioError,
    trace_to_replay_scenario,
    write_decision_points_jsonl,
)
from .sft import SftConversionError, infer_tool_schemas, trace_to_sft_example
from .store import JsonlTraceStore, TraceValidationError
from .teacher_quality import (
    PUBLIC_TEACHER_EGRESS_SCOPE,
    PUBLIC_TEACHER_SOURCE_KINDS,
    audit_teacher_trace,
    compact_audit_record,
    task_fingerprint,
    validate_external_teacher_batch,
    validate_external_teacher_task,
)

__all__ = [
    "EventKind",
    "EvidencePolicyDecision",
    "EvidencePolicyGuard",
    "EvidencePolicyMode",
    "EvidencePolicyVerdict",
    "CACHE_SCHEMA_VERSION",
    "DECISION_POINT_SCHEMA_VERSION",
    "JsonlTraceStore",
    "ObservationCache",
    "ObservationCacheEntry",
    "ObservationCacheStore",
    "FORCED_STOP_FLAG",
    "PLANNER_BUDGET_PROTOCOL",
    "ParsedPlannerPrediction",
    "PlannerBudgetMiddleware",
    "PlannerBudgetState",
    "PlannerAction",
    "PlannerActionKind",
    "PlannerDecisionPoint",
    "PlannerDecisionEvaluation",
    "PlannerPredictionError",
    "PlannerPredictionRecord",
    "PlannerSftConversionError",
    "PUBLIC_TEACHER_EGRESS_SCOPE",
    "PUBLIC_TEACHER_SOURCE_KINDS",
    "ReplayCacheConflict",
    "ReplayCacheMiss",
    "ReplayError",
    "ReplaySession",
    "ReplayScenario",
    "ReplayScenarioStore",
    "ReplayTranscript",
    "RunOutcome",
    "SftConversionError",
    "SCENARIO_SCHEMA_VERSION",
    "ScenarioError",
    "TraceEvent",
    "TraceRecorder",
    "TraceValidationError",
    "canonical_tool_signature",
    "content_digest",
    "count_prior_tool_calls",
    "aggregate_planner_evaluations",
    "assistant_supervision_indices",
    "audit_teacher_trace",
    "compact_audit_record",
    "evaluate_planner_prediction",
    "evaluate_prediction_records",
    "infer_tool_schemas",
    "inject_budget_state_into_messages",
    "parse_planner_prediction",
    "planner_decision_to_sft_example",
    "planner_budget_state",
    "rebuild_transcript",
    "render_budget_prompt",
    "trace_to_replay_scenario",
    "trace_to_sft_example",
    "tool_family",
    "task_fingerprint",
    "validate_external_teacher_batch",
    "validate_external_teacher_task",
    "write_decision_points_jsonl",
    "write_planner_sft_jsonl",
]
